# ===============================
# Application
# ===============================
spring.application.name=chessnalysis-backend
server.port=8080

# ===============================
# Datasource (temporary local config)
# Replace later with Supabase
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.txxmtfpnjazclpdvqsov&password=chessnalysis
spring.datasource.username=chessnalysis
spring.datasource.password=chessnalysis
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO

# ===============================
# JWT (placeholder values)
# ===============================
security.jwt.secret=change-this-secret-before-prod
security.jwt.expiration-ms=3600000

# ===============================
# WebSocket
# ===============================
spring.websocket.message-broker.enabled=true